runtime: python27
api_version: 1
threadsafe: yes

handlers:
    
- url: /(.*\.html)
  static_files: dist/revamped-personal-site/\1
  upload: dist/revamped-personal-site/(.*\.html)

- url: /(.*\.css)
  static_files: dist/revamped-personal-site/\1
  upload: dist/revamped-personal-site/(.*\.css)

- url: /(.*\.js)
  static_files: dist/revamped-personal-site/\1
  upload: dist/revamped-personal-site/(.*\.js)

- url: /(.*\.png)
  static_files: dist/revamped-personal-site/\1
  upload: dist/revamped-personal-site/assets/images/(.*\.png)

- url: /(.*\.jpg)
  static_files: dist/revamped-personal-site/\1
  upload: dist/revamped-personal-site/assets/images/(.*\.jpg)

- url: /(.*\.jpeg)
  static_files: dist/revamped-personal-site/\1
  upload: dist/revamped-personal-site/(.*\.jpeg)

- url: /(.*\.pdf)
  static_files: dist/revamped-personal-site/\1
  upload: dist/revamped-personal-site/assets/pdfs/(.*\.pdf)

- url: /(.*\.ttf)
  static_files: dist/revamped-personal-site/\1
  upload: dist/revamped-personal-site/assets/fonts/*/(.*\.ttf)

- url: /(.*\.svg)
  static_files: dist/revamped-personal-site/\1
  upload: dist/revamped-personal-site/assets/images/*/(.*\.svg)

# Site root.
- url: /
  static_files: dist/revamped-personal-site/index.html
  upload: dist/revamped-personal-site/index.html

# Catch-all rule, responsible from handling Angular application routes (deeplinks).
- url: /.*
  static_files: dist/revamped-personal-site/index.html
  upload: dist/revamped-personal-site/index.html

- url: /favicon\.ico
  static_files: dist/revamped-personal-site/\1
  upload: dist/favicon.ico

skip_files:
- ^(?!dist)