import { PortfolioItem } from '../../models/portfolio';

export const portfolioItems: PortfolioItem[] = [
    { description: 'Mobile app allowing users to listen to Farsi Audiobooks in their native language', subTitle: 'Farsi Audiobooks', url: 'https://www.maktub.app', id: 'maktub', title: 'Maktub App', imgSrc: 'assets/images/maktub-app.jpg', technologies: ['React Native', 'Typescript', 'Firebase', 'Fastlane'], images: ['/assets/images/maktub-slide1.png', '/assets/images/maktub-slide2.png'] },
    { description: 'Business Page for Atlantic Graffiti Removal Services in Halifax, NS', subTitle: 'Graffiti Removal Business', url: 'https://www.atlanticgraffitiremoval.com', id: 'agr', title: 'Atlantic Graffiti Removal', imgSrc: 'assets/images/agr-app.png', technologies: ['C#', 'ASP.NET', 'Azure'], images: ['/assets/images/agr-slide1.png', '/assets/images/agr-slide2.png', '/assets/images/agr-slide3.png'] },
    { description: 'In-person tire changing PWA servicing the GTA', subTitle: 'Tire Changing PWA', url: 'https://www.tread2go.com/', id: 'ttg', title: "Tread 2 Go", imgSrc: 'assets/images/tread2go.png', technologies: ['Angular', 'Angular Material', 'Typescript', 'NGRX', 'PWA', 'AWS Cognito'], images: ['/assets/images/maktub-slide1.png'] },
    { description: 'Online ledger allowing for wallet to wallet cryptocurrenct transactions', subTitle: 'Cryptocurrency Payment App', id: 'raly', title: 'Raly Payments', imgSrc: 'assets/images/raly.png', technologies: ['React Native', 'Typescript', 'Golang', 'Google Cloud Platforms', 'Fastlane'], images: ['/assets/images/maktub-slide1.png'] },
    { description: 'Web application meant to help organizations prediect infastructure downtime', subTitle: 'Predictive Analyics Dashboard', url: 'https://www.predikat.co/product.html', id: 'predikat', title: 'Predikat Predicative Analytics', imgSrc: 'assets/images/predikat.png', technologies: ['React', 'AWS Cognito'], images: ['/assets/images/maktub-slide1.png'] },
    { description: 'Web and PWA deal-finding app serving the GTA', subTitle: 'Local Deals Web App and PWA', url: 'https://lastcall.cc/', id: 'lastCall', title: 'Last Call', imgSrc: 'assets/images/lastcall.png', technologies: ['Angular', 'Typescript', 'Google Cloud Platforms', 'Firebase', 'PWA'], images: ['/assets/images/maktub-slide1.png'] }
];